identifier:
  image: semtech/mu-identifier
  links:
    - dispatcher:dispatcher
  ports:
    - "80:80"
dispatcher:
  image: semtech/mu-dispatcher
  links:
    - registration:registration
    - login:login
    - file:file
    - resource:resource
  volumes:
    - ./config:/config
db:
  image: tenforce/virtuoso:virtuoso-v7.2.0-latest
  environment:
    SPARQL_UPDATE: "true"
  ports:
    - "8890:8890"
  volumes:
    - /home/erika/mu-semtech/docker-data/virtuoso:/var/lib/virtuoso/db
registration:
  image: semtech/mu-registration-service
  links:
    - db:database
  environment:
    MU_APPLICATION_GRAPH: http://mu.semte.ch/application
    MU_APPLICATION_SALT: mysupersecretsaltchangeme
login:
  image: semtech/mu-login-service
  links:
    - db:database
  environment:
    MU_APPLICATION_GRAPH: http://mu.semte.ch/application
    MU_APPLICATION_SALT: mysupersecretsaltchangeme
file:
  image: semtech/mu-file-service
  links: 
    - db:database
  volumes:
    - /tmp/storage:/home/app/storage
  environment:
    MU_APPLICATION_GRAPH: http://mu.semte.ch/application
    SECRET_KEY_BASE: my-secret-production-key-for-rails
resource:
  image: semtech/mu-cl-resources
  links:
    - db:database
  volumes:
    - ./config/resources:/config
  environment:
    BOOT: mu-cl-resources