version: '3.4'
services:
  frontend:
    image: bravoer/music-crm-frontend:1.1.0
    links:
      - identifier:backend
  identifier:
    image: semtech/mu-identifier:1.5.0
    environment:
      MU_ENCRYPTION_SALT: mysecret
      MU_SIGNING_SALT: anothersecret
      MU_SECRET_KEY_BASE: yetanothersecretthatmustbeatleastsixtyforcharacterslongfoobarbazzzzz
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
  database:
    image: tenforce/virtuoso:1.1.0-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./database:/data
  registration:
    image: semtech/mu-registration-service:2.6.0
    environment:
      MU_APPLICATION_SALT: ''
  login:
    image: semtech/mu-login-service:2.8.0
    environment:
      MU_APPLICATION_SALT: ''
  authorization:
    image: semtech/mu-authorization-service:0.1.0
  userprofile:
    image: bravoer/user-profile-service:0.3.0
  file:
    image: semtech/mu-file-service:2.4.0
    volumes:
      - ./storage:/data
    environment:
      SECRET_KEY_BASE: my-secret-production-key-for-rails
      MU_APPLICATION_MAX_FILE_SIZE: 50M
      STREAMING: "true"
  cache:
    image: semtech/mu-cache:0.6.0
    links:
    - resource:backend
  resource:
    image: semtech/mu-cl-resources:1.17.1
    volumes:
      - ./config/resources:/config
  migrations:
    image: semtech/mu-migrations-service:0.4.0
    volumes:
      - ./config/migrations:/data/migrations
  export:
    image: semtech/mu-export-service:1.0.0
    volumes:
      - ./config/export:/config
  labels:
    image: bravoer/label-printer-service:1.0.0
  search:
    image: bravoer/advanced-search-service:1.1.0

