frontend:
  image: semtech/ember-proxy-service:1.1.0
  volumes:
    - ./client/dist:/app
    - ./config/spa-proxy:/config
  links:
    - identifier:backend
  ports:
    - "80:80"
  environment:
    VIRTUAL_HOST: "bravoer.semte.ch,backstage.bravoer.be"
    LETSENCRYPT_HOST: "bravoer.semte.ch,backstage.bravoer.be"
    LETSENCRYPT_EMAIL: "erika.pauwels@gmail.com"
    STATIC_FOLDERS_REGEX: "^/(assets|font|files)/"
identifier:
  image: semtech/mu-identifier:1.0.0
  links:
    - dispatcher:dispatcher
  # ports:
  #   - "80:80"
dispatcher:
  image: semtech/mu-dispatcher:1.0.1
  links:
    - registration:registration
    - login:login
    - authorization:authorization
    - userprofile:userprofile
    - file:file
    - resource:resource
  volumes:
    - ./config:/config
db:
  image: tenforce/virtuoso:1.0.0-virtuoso7.2.2
  environment:
    SPARQL_UPDATE: "true"
  ports:
    - "8890:8890"
  volumes:
    - ./virtuoso:/data
registration:
  image: semtech/mu-registration-service:2.4.0
  links:
    - db:database
  environment:
    MU_APPLICATION_SALT: mysupersecretsaltchangeme
login:
  image: semtech/mu-login-service:2.5.0
  links:
    - db:database
  environment:
    MU_APPLICATION_SALT: mysupersecretsaltchangeme
authorization:
  image: semtech/mu-authorization-service:latest
  links:
    - db:database
userprofile:
  image: bravoer/user-profile-service:0.1.0
  links:
    - db:database
file:
  image: semtech/mu-file-service:2.3.0
  links: 
    - db:database
  volumes:
    - ./storage:/data
  environment:
    SECRET_KEY_BASE: my-secret-production-key-for-rails
    MU_APPLICATION_MAX_FILE_SIZE: 50M
resource:
  image: semtech/mu-cl-resources:1.10.4
  links:
    - db:database
  volumes:
    - ./config/resources:/config
