version: '2'
services:
  # frontend:
  #   image: semtech/ember-proxy-service:1.1.0
  #   volumes:
  #     - ./client/dist:/app
  #     - ./config/spa-proxy:/config
  #   links:
  #     - identifier:backend
  #   ports:
  #     - "80:80"
  #   environment:
  #     VIRTUAL_HOST: "bravoer.semte.ch,backstage.bravoer.be"
  #     LETSENCRYPT_HOST: "bravoer.semte.ch,backstage.bravoer.be"
  #     LETSENCRYPT_EMAIL: "erika.pauwels@gmail.com"
  #     STATIC_FOLDERS_REGEX: "^/(assets|font|files|export|label-printer)/"
  identifier:
    image: semtech/mu-identifier:1.2.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
    environment:
      MU_ENCRYPTION_SALT: mysecret
      MU_SIGNING_SALT: anothersecret
      MU_SECRET_KEY_BASE: yetanothersecretthatmustbeatleastsixtyforcharacterslongfoobarbazzzzz
  dispatcher:
    image: semtech/mu-dispatcher:1.1.0
    links:
      - registration:registration
      - login:login
      - authorization:authorization
      - userprofile:userprofile
      - file:file
      - cache:cache
      - export:export
      - labels:labels
      - search:search
    volumes:
      - ./config:/config
  db:
    image: tenforce/virtuoso:1.1.0-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
    ports:
      - "8890:8890"
    volumes:
      - ./virtuoso:/data
  registration:
    image: semtech/mu-registration-service:2.5.0
    links:
      - db:database
    env_file:
      - ./environment/authentication.env
  login:
    image: semtech/mu-login-service:2.7.0
    links:
      - db:database
    env_file:
      - ./environment/authentication.env
  authorization:
    image: semtech/mu-authorization-service:0.1.0
    links:
      - db:database
  userprofile:
    image: bravoer/user-profile-service:0.3.0
    links:
      - db:database
  file:
    image: semtech/mu-file-service:2.4.0
    links: 
      - db:database
    volumes:
      - ./storage:/data
    environment:
      SECRET_KEY_BASE: my-secret-production-key-for-rails
      MU_APPLICATION_MAX_FILE_SIZE: 50M
      STREAMING: "true"
  cache:
    image: semtech/mu-cache:0.5.0
    links:
    - resource:resource
    environment:
      CACHE_BACKEND: http://resource/
  resource:
    image: semtech/mu-cl-resources:1.15.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  migrations:
    image: semtech/mu-migrations-service:0.2.0
    links:
      - db:database
    volumes:
      - ./migrations:/data/migrations
  export:
    image: semtech/mu-export-service:1.0.0
    volumes:
      - ./config/export:/config
    links:
      - db:database
  labels:
    image: bravoer/label-printer-service:1.0.0
    links:
      - db:database
  search:
    image: bravoer/advanced-search-service:1.0.0
    links:
      - db:database
