# frontend:
#   image: semtech/mu-nginx-spa-proxy:1.0.1
#   volumes:
#     - ./client/dist:/app
#   links:
#     - identifier:backend
#   ports:
#     - "80:80"
#   environment:
#     VIRTUAL_HOST: "bravoer.semte.ch,backstage.bravoer.be"
#     LETSENCRYPT_HOST: "bravoer.semte.ch,backstage.bravoer.be"
#     LETSENCRYPT_EMAIL: "erika.pauwels@gmail.com"
#     STATIC_FOLDERS_REGEX: "^/(assets|font|files)/"
identifier:
  image: semtech/mu-identifier:1.0.0
  links:
    - dispatcher:dispatcher
dispatcher:
  image: semtech/mu-dispatcher:1.0.1
  links:
    - registration:registration
    - login:login
    - file:file
    - resource:resource
    - userprofile:userprofile
  volumes:
    - ./config:/config
db:
  image: tenforce/virtuoso:1.0.0-virtuoso7.2.2
  environment:
    SPARQL_UPDATE: "true"
  ports:
    - "8890:8890"
  volumes:
    - ./virtuoso:/data
registration:
  image: semtech/mu-registration-service:2.4.0
  links:
    - db:database
  environment:
    MU_APPLICATION_SALT: mysupersecretsaltchangeme
login:
  image: semtech/mu-login-service:2.5.0
  links:
    - db:database
  environment:
    MU_APPLICATION_SALT: mysupersecretsaltchangeme
userprofile:
  image: erikap/brav-user-profile-service:0.1.0
  links:
    - db:database
file:
  image: semtech/mu-file-service:2.1.0
  links: 
    - db:database
  volumes:
    - ./storage:/home/app/storage
  environment:
    SECRET_KEY_BASE: my-secret-production-key-for-rails
resource:
  image: semtech/mu-cl-resources:1.10.2
  links:
    - db:database
  volumes:
    - ./config/resources:/config
  environment:
    BOOT: mu-cl-resources
