frontend:
  image: semtech/mu-nginx-spa-proxy
  volumes:
    - ./client/dist:/app
  links:
    - identifier:backend
  ports:
    - "80:80"
  environment:
    VIRTUAL_HOST: "bravoer.semte.ch,backstage.bravoer.be"
    LETSENCRYPT_HOST: "bravoer.semte.ch,backstage.bravoer.be"
    LETSENCRYPT_EMAIL: "erika.pauwels@gmail.com"
identifier:
  image: semtech/mu-identifier:1.0.0
  links:
    - dispatcher:dispatcher
dispatcher:
  image: semtech/mu-dispatcher:1.0.0
  links:
    - registration:registration
    - login:login
    - file:file
    - resource:resource
  volumes:
    - ./config:/config
db:
  image: tenforce/virtuoso:virtuoso-v7.2.0-latest
  environment:
    SPARQL_UPDATE: "true"
  ports:
    - "8890:8890"
  volumes:
    - ./virtuoso:/var/lib/virtuoso/db
registration:
  image: semtech/mu-registration-service:2.0.1
  links:
    - db:database
  environment:
    MU_APPLICATION_GRAPH: http://mu.semte.ch/application
    MU_APPLICATION_SALT: mysupersecretsaltchangeme
login:
  image: semtech/mu-login-service:2.0.1
  links:
    - db:database
  environment:
    MU_APPLICATION_GRAPH: http://mu.semte.ch/application
    MU_APPLICATION_SALT: mysupersecretsaltchangeme
file:
  image: semtech/mu-file-service:2.0.0
  links: 
    - db:database
  volumes:
    - ./storage:/home/app/storage
  environment:
    MU_APPLICATION_GRAPH: http://mu.semte.ch/application
    SECRET_KEY_BASE: my-secret-production-key-for-rails
resource:
  image: semtech/mu-cl-resources:1.0.2
  links:
    - db:database
  volumes:
    - ./config/resources:/config
  environment:
    BOOT: mu-cl-resources